// hr-intent.enum.ts

export enum HrIntent {
  ASK_NAME = 'ASK_NAME',
  ASK_COMPANY = 'ASK_COMPANY',
  ASK_EXPERIENCE = 'ASK_EXPERIENCE',
  ASK_SKILL = 'ASK_SKILL',
  ASK_PROJECT = 'ASK_PROJECT',
  ASK_JD_MATCH = 'ASK_JD_MATCH',
  ASK_OWNERSHIP = 'ASK_OWNERSHIP',
  ASK_CONTACT = 'ASK_CONTACT',
  UNKNOWN = 'UNKNOWN',
}
